version: "3.5"
services:
#  backend:
#    image: node:10
#    container_name: ${PROJECT_NAME}-backend
#    user: "node"
#    working_dir: /home/node/app
#    command: yarn dev
#    environment:
#      - NODE_ENV=${NODE_ENV}
#      - DB_URI='mongodb://schoology-db/schoology'
#      - DROP_DATABASE=true
#      - REPLACE_ID=true
#    ports:
#      - "${DOCKER_DB_PORT}:3000"
#    volumes:
#      - ./backend/:/home/node/app
#    depends_on:
#      - db
#    networks:
#      - ${PROJECT_NAME}-network

  frontend:
    image: node:14
    container_name: ${PROJECT_NAME}-frontend
    user: "node"
    working_dir: /home/node/app
    command: yarn start
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${DOCKER_FRONTEND_PORT}:3000"
    volumes:
      - ./frontend/:/home/node/app
    networks:
      - ${PROJECT_NAME}-network

#  db:
#    image: "mongo"
#    container_name: ${PROJECT_NAME}-db
#    ports:
#      - "${DOCKER_DB_PORT}:27017"
#    volumes:
#      - ./.docker/data/db:/home/data
#    networks:
#      - ${PROJECT_NAME}-network

networks:
  control-savings-network:
    driver: bridge